### ISSUE TITLE
Can't find jni4net.j-0.8.8.0.jar in escaped path. Version 5.3.0.3

### ISSUE THREAD

**Issue by kennylerma** [fdorg/flashdevelop#1787]
Escaping the path below is causing an issue finding the needed java files.  The jar file is indeed located at this path on my install of FlashDevelop. 

C:\Program%20Files%20(x86)\FlashDevelop\Plugins\jni4net.j-0.8.8.0.jar

Temporary fix:  I copied the java files below to the FlashDevelop root folder as below.
jni4net.j-0.8.8.0.jar
jni4net.n.w32.v20-0.8.8.0.dll
jni4net.n.w32.v40-0.8.8.0.dll

Copy to root folder
c:\program files (x86)\flashdevelop\

**Comment by pzahra** [comment]
Temporary fix didn't work for me. This happens on first run:
```
Error details: net.sf.jni4net.jni.JNIException: Can't load java class for flash.tools.debugger.concrete.DValue_ from classLoader sun.misc.Launcher$AppClassLoader@186d4c1 ---> java.lang.LinkageError: flash/tools/debugger/concrete/DValue_ : Unsupported major.minor version 52.0
   at net.sf.jni4net.jni.JNIEnv.ExceptionTest()
   at net.sf.jni4net.jni.JNIEnv.CallObjectMethodPtr(IJvmProxy obj, MethodId methodIdNative, Value[] args)
   at java.lang.ClassLoader.loadClass(String par0)
   at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
   --- End of inner exception stack trace ---
   at net.sf.jni4net.utils.Registry.LoadClass(String name, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterClass(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, ClassLoader classLoader, JNIEnv env)
   at net.sf.jni4net.utils.Registry.BindJvm(RegistryRecord record, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterType(Type type, Boolean bindJVM, JNIEnv env)
   at net.sf.jni4net.utils.Registry.RegisterAssembly(Assembly assembly, Boolean bindJVM)
   at net.sf.jni4net.Bridge.RegisterAssembly(Assembly assembly)
   at FlashDebugger.DebuggerManager.Start(Boolean alwaysStart)
```

Subsequent runs show no message in output, but popup says "Internal Debugger Exception". Log says:

```System.NullReferenceException: Object reference not set to an instance of an object.
   at net.sf.jni4net.jni.JNIEnv.CallStaticObjectMethodPtr(Class clazz, MethodId methodIdNative, Value[] args)
   at flash.tools.debugger.Bootstrap.sessionManager()
   at FlashDebugger.FlashInterface.Start()
   at FlashDebugger.DebuggerManager.bgWorker_DoWork(Object sender, DoWorkEventArgs e)
```

**Comment by Meychi** [comment]
@SlavaRa, @Neverbirth?

**Comment by SlavaRa** [comment]
@kennylerma please check latest development build

**Comment by Neverbirth** [comment]
Actually this is a bug in latest Jni4Net that I fixed 2.5 years ago, and was merged in the official repository (https://github.com/jni4net/jni4net/commit/fab0ea8488f4310f7294dfede9d225542261d61a), however the latest binary distributed is from September 2014, before the fix.

The binary we had before was compiled by us, and I was expecting there was some new official release since then as there are also other fixes and improvements on the repo (not that many sadly).

**Comment by Neverbirth** [comment]
Fixed in https://ci.appveyor.com/api/buildjobs/pb46pxtxd6362jce/artifacts/FlashDevelop%2FInstaller%2FBinary%2FFlashDevelopPR_1956.zip

Should be merged soon.

**Comment by mepsoid** [comment]
In mid 2019 latest version is 5.3.0.3 and problem still persists...

**Comment by SlavaRa** [comment]
Please try development-build http://flashdevelop.org/downloads/builds/ ;)
