### ISSUE TITLE
Window position (start on display #2) not remembered in my display configuration

### ISSUE THREAD

**Issue by gene-pavlovsky** [fdorg/flashdevelop#856]
FlashDevelop can't remember the last used monitor/position. My display settings are like this:
![Settings](http://i.imgur.com/ebURuiy.png)
Display 1 is my laptop, and Display 2 is an external wall-mounted monitor, above my laptop. When I start FD, it always appears on laptop's screen, but I want it to start on the other screen. I tried un-maximizing FD window, moving it to screen 2, then restarting FD, then maximizing the window again. Most apps with "remember window size&position" feature usually remember which screen to start on after this procedure, but not in my case. Maybe it's related to my particular screen arrangement. Since screen 2 is above and to the left from screen 1, when FD is on screen 2, it's actual window position is -1920, -1080 (FlashDevelop Settings > State). Maybe the position doesn't get remembered or restored because negative coordinates are not handled correctly? For now as a work-around I have to use an AHK script which triggers after I launch FlashDevelop with a hotkey
```autohotkey
      WinWait, ahk_exe FlashDevelop.exe
      if WinExist("ahk_exe FlashDevelop.exe") {
         WinRestore
         WinMove -1920, -1080
         WinMaximize
         WinActivate
      }
```

**Comment by Meychi** [comment]
There are cases where negative values are truly incorrect and we forcefully restore them so the FD doesn't open in incorrect negative positions.

This needs better logic to handle screen correctly and we dont have proper setups to test.

**Comment by gene-pavlovsky** [comment]
If you plan to work on it one day, I could do some testing with different layouts (with my 2 screens, don't have 3 unfortunately).

**Comment by wise0704** [comment]
@gene-pavlovsky Could you please test out #1267? It should be working but just to make sure.

**Comment by gene-pavlovsky** [comment]
It's real nice to hear that you fixed it! Unfortunately can't test since we had to move, and I've left my second monitor behind. Developing on a 12.5" laptop screen now...

**Comment by gene-pavlovsky** [comment]
Thanks for the fix, I'll test whenever I have chance, and report back if still have any problem :)
